app_config:
  # Name of the app, with underscores.
  app_name: my_app
  # Real text name of the app, in human language.
  app_title: My App
  # If true, use Rails API mode, which does not provide views and is used e.g.
  # for SPA's or only talking to other services.
  api: false
  # Use ActiveRecord to talk to a database.
  use_database: true
  # Use mysql or postgres as the database. Flipp primarily supports MySQL
  # unless there is a pressing need.
  database: mysql
  # Create controllers. You can set this to false if you're creating a Kafka-only
  # service.
  use_controllers: true
  # Create views. This should always be true if the api setting is false.
  use_views: true
  # Create models and controller code to enable Flipp's Single Sign On gateway
  # so that only people signed in can access it. Requires both views and
  # a database.
  use_sso: false
  # Create Kafka configuration to be able to produce or consume.
  use_kafka: true
  # Use Kafka consumers as the primary command. This will generate consumer code
  # and config as well as switching the command from `rails server` to `rails deimos:start`.
  use_kafka_consumers: true
  # Create webpack config files for the frontend.
  use_webpack: false
  # Create React files for the frontend.
  use_react: false
  # Add Flipp's one-click-dev scripts.
  use_one_click_dev: true
  # Slack channel to use for Datadog monitors.
  slack_channel: 'my-team-channel'
  # OpsGenie team to use for Datadog monitors.
  ops_genie_team: 'my_app'

