default: &default
  adapter: mysql2
  encoding: utf8mb4
  host: <%= ENV['DB_HOST'] || '127.0.0.1' %>
  port: 3306
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 10
  reconnect: true

development: &development
  <<: *default
  database: my_app_development
  username: <%= ENV['MY_APP_DB_USERNAME'] || 'root' %>
  password: <%= ENV['MY_APP_DB_PASSWORD'] %>

test:
  <<: *development
  database: my_app_test

staging:
  <<: *default
  host: <%= ENV['DB_HOST'] %>
  database: my_app_staging
  username: my_app
  password: <%= ENV['DB_PASSWORD'] %>

production:
  <<: *default
  host: <%= ENV['DB_HOST'] %>
  database: my_app_production
  username: my_app
  password: <%= ENV['DB_PASSWORD'] %>
