# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 055c86405118a8ba351f507eed86eb54936b84fde287b163aec55851be84ef9c75fd9a7bee04bacb6f7f3a8910b9188b7a4f4272025eee37e5a7637c6f35be52

test:
  secret_key_base: d416247e80b55ac8ed11f7d4cbeb4e992b48e63b8b6edb363c651c99e3c93e604c50c855188b72dc79f74a3300244481eb00e0c4b50bc4426bce20a0eef9b3df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
